// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzQjZ7Z8Ngg9X3t7SF8oo5pIBqxM-VEU',
    appId: '1:380740161956:web:4cf056275124ef34a67131',
    messagingSenderId: '380740161956',
    projectId: 'sphero-swarm',
    authDomain: 'sphero-swarm.firebaseapp.com',
    databaseURL: 'https://sphero-swarm-default-rtdb.firebaseio.com',
    storageBucket: 'sphero-swarm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1SHhanMIqPgdJV3apDR4d9WpTW-yxOE',
    appId: '1:380740161956:android:e36bcc0ec86f1242a67131',
    messagingSenderId: '380740161956',
    projectId: 'sphero-swarm',
    databaseURL: 'https://sphero-swarm-default-rtdb.firebaseio.com',
    storageBucket: 'sphero-swarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_5M-ufRJmA5fSqqvU2Nunpg2Dqsn-m4',
    appId: '1:380740161956:ios:4c32d8d5699c9631a67131',
    messagingSenderId: '380740161956',
    projectId: 'sphero-swarm',
    databaseURL: 'https://sphero-swarm-default-rtdb.firebaseio.com',
    storageBucket: 'sphero-swarm.appspot.com',
    iosBundleId: 'com.example.spheroSwarmInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_5M-ufRJmA5fSqqvU2Nunpg2Dqsn-m4',
    appId: '1:380740161956:ios:4c32d8d5699c9631a67131',
    messagingSenderId: '380740161956',
    projectId: 'sphero-swarm',
    databaseURL: 'https://sphero-swarm-default-rtdb.firebaseio.com',
    storageBucket: 'sphero-swarm.appspot.com',
    iosBundleId: 'com.example.spheroSwarmInterface',
  );
}
